"""Writes `src/settings/tables.rs` from the `env` section of `config_golden.json`.

The tables (transcription languages, weight types, engines, OCR languages) are what Python's
`config.py` takes from its model modules. The golden records them from the real code, so the Rust
constants are generated from it and `tests/settings_system.rs` compares them with it again.

Run after `regenerate_config_golden.py`:  python generate_settings_tables.py
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
TARGET = HERE.parents[1] / "src" / "settings" / "tables.rs"

env = json.loads((HERE / "config_golden.json").read_text(encoding="utf-8"))["env"]


def text(value):
    return json.dumps(value, ensure_ascii=False)


def strings(name, doc, values):
    body = "".join(f"    {text(v)},\n" for v in values)
    return f"/// {doc}\npub const {name}: &[&str] = &[\n{body}];\n"


out = [
    "//! The language, engine and weight-type tables the settings are checked against.\n",
    "//!\n",
    "//! Generated by `tests/fixtures/generate_settings_tables.py` from what Python's `config.py` read out\n",
    "//! of its model modules; `tests/settings_system.rs` compares them with the golden again.\n\n",
    strings("CTRANSLATE2_WEIGHT_TYPES", "Local translation models, smallest first.", env["ctranslate2_weight_types"]),
    "\n",
    strings("WHISPER_WEIGHT_TYPES", "Local Whisper models.", env["whisper_weight_types"]),
    "\n",
    strings("TRANSLATION_ENGINES", "Translation engines in the order the UI lists them.", env["translation_engines"]),
    "\n",
    strings("TRANSCRIPTION_ENGINES", "Speech-to-text engines.", env["transcription_engines"]),
    "\n",
    strings("OCR_SOURCE_LANGUAGES", "Languages the OCR can be told to read.", env["ocr_source_languages"]),
    "\n/// Transcription language -> the countries it is offered for, in the order Python lists them.\n",
    "pub const TRANSCRIPTION_LANGUAGES: &[(&str, &[&str])] = &[\n",
]
for language, countries in env["transcription_languages"].items():
    inner = ", ".join(text(c) for c in countries)
    out.append(f"    ({text(language)}, &[{inner}]),\n")
out.append("];\n")

TARGET.write_text("".join(out), encoding="utf-8", newline="\n")
print(f"{len(env['transcription_languages'])} languages -> {TARGET}")
