//! Display language names to each engine's own codes.
//!
//! The table is Python's `languages.yml` as JSON (`assets/languages.json`,
//! regenerated by `tests/fixtures/regenerate_languages_golden.py`), and
//! `language_codes` is `Translator.getLanguageCode`, special cases included.

use std::sync::OnceLock;

use serde_json::Value;

fn table() -> &'static Value {
    static TABLE: OnceLock<Value> = OnceLock::new();
    TABLE.get_or_init(|| {
        serde_json::from_str(include_str!("assets/languages.json"))
            .expect("languages.json is valid JSON")
    })
}

pub fn source_languages(engine: &str, weight: &str) -> Vec<String> {
    let scope = if engine == "CTranslate2" {
        &table()[engine][weight]
    } else {
        &table()[engine]
    };
    scope["source"]
        .as_object()
        .into_iter()
        .flatten()
        .map(|(name, _)| name.clone())
        .collect()
}

/// The engine does not know one of the languages (or the engine itself).
/// Python raises `UnsupportedLanguageError`; callers answer "not supported",
/// which is not a failure of the engine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Unsupported(pub String);

impl std::fmt::Display for Unsupported {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// DeepL has no plain "English" or "Portuguese" target: the country picks the variant.
fn deepl_target(target: &str, country: &str) -> String {
    match target {
        "English" if ["United States", "Canada", "Philippines"].contains(&country) => {
            "English American".into()
        }
        "English" => "English British".into(),
        "Portuguese" if country == "Portugal" => "Portuguese European".into(),
        "Portuguese" => "Portuguese Brazilian".into(),
        other => other.into(),
    }
}

/// `(source code, target code)` for `engine`. `weight_type` only matters for
/// CTranslate2, whose languages depend on the model.
pub fn language_codes(
    engine: &str,
    weight_type: &str,
    country: &str,
    source: &str,
    target: &str,
) -> Result<(String, String), Unsupported> {
    let unsupported = || {
        Unsupported(format!(
            "{engine} does not support language (source={source:?}, target={target:?})"
        ))
    };
    let scope = match engine {
        "CTranslate2" => table()
            .get(engine)
            .and_then(|weights| weights.get(weight_type)),
        _ => table().get(engine),
    }
    .ok_or_else(unsupported)?;
    let target = if engine == "DeepL_API" {
        deepl_target(target, country)
    } else {
        target.to_string()
    };
    let code = |side: &str, name: &str| {
        scope
            .get(side)
            .and_then(|names| names.get(name))
            .and_then(Value::as_str)
    };
    match (code("source", source), code("target", &target)) {
        (Some(source), Some(target)) => Ok((source.to_string(), target.to_string())),
        _ => Err(unsupported()),
    }
}
